appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DvbjXDbUIF2HZ4W4hl5UP9VgpW9oCEeU+6TadZ4VS6BtfuOhJkITYN8uH526/GjGwIFZcX/pb00RpKhpCuPEsjUz9msI2GU2GXx3bQFH74GSgE02yelU6L55DYU4VBl7pKuncWLJ59/rUPyCkvQUCxFJPvWEmCnZW6BC8NU6DEy+x6AAPDxukdfwnPiaY9EzTmS2NiEsVkczQgO7rvez1T3tgQI7SbjJiTVyf3M2CuHHEIYTW29Kt3dYC/qGeBTkdO3cMRE0f2UkdYkNL8wAHVbu5G7Q4sjnmwwE9vFDD11NY3f11kCuzVPz1Ux8WwFc/V/6w6a5ajnkm42Wbj2tqwBU+XrWy1a3Nvro+impucuQ4hAcmLwF4lwzPGlBRpQeersNPYQ3pRD6Sk0mYteVekz6piqjW5oBgtkXUG8ZZIueyqMcIEN1/Br02v1e3BKyiWWYjTC/gERk0ox4xkRbJd6w2D9m2gVTbDeYSsmXnwcfk0O9ORSde4h6gnG6uJfOmRFohNsUtVSgWfKZgCMM7h1na3qVjCQIgR30DJhogMljPUexAYRc4aRY/ucxj7gpC9FPLZDiS0gLF++A1QkID3CkuJE4LlipFq9leVKRqMKeB4mIAf6M6RYB8z+QvFbigEwtZDmLcDpQmr9IgMO+xdevUG9rVfSEPoFeQXsMjSQ=}
